from . import destination
from . import product
from . import product_template
from . import sale_order
from . import sale_order_line
from . import travel_line_details
from . import pricelist
from . import account_move
from . import res_partner
from . import pax
from . import airline
