repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Utilisez la dernière version stable
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Version compatible
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/OCA/odoo-pre-commit-hooks
    rev: v0.0.35
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po
        args: ["--fix"]
