{
    "name": "Travel Agency",
    "version": "16.0.1.0.0",
    "author": "OpenJAF, Business Solutions For Africa",
    "maintainer": "Vincent LUBA",
    "website": "https://www.biz-4-africa.com/odoo-travel",
    "category": "Sales",
    "description": ("Travel Agency"),
    "depends": [
        "travel_activity",
        "travel_car",
        "travel_flight",
        "travel_hotel",
        "travel_misc",
        "travel_visa",
        "travel_package",
        "travel_transfer",
        # "website_sale_extension",
    ],
    "data": [],
    "demo": [],
    "application": True,
    "installable": True,
    "license": "OPL-1",
}
