{
    "name": "Travel Agency - Hotels",
    "version": "16.0.1.0.0",
    "author": "OpenJAF, Business Solutions For Africa",
    "maintainer": "Vincent LUBA",
    "website": "https://www.biz-4-africa.com/odoo-travel",
    "category": "Sales",
    "description": ("Travel Agency - Hotels"),
    "depends": ["travel_core", "account_reports", "account"],
    "data": [
        "data/categories.xml",
        "data/attributes.xml",
        "data/demo_data.xml",
        # 'data/partner_ledger.xml',
        "views/product_template.xml",
        "views/sale_order.xml",
        "views/allotment.xml",
        "views/sale_order_line.xml",
        "views/travel_line_details.xml",
        "views/account_move.xml",
        "views/hotel.xml",
        "wizard/hotel.xml",
        "security/ir.model.access.csv",
        "report/hotel_voucher.xml",
        "report/hotel_estimate.xml",
        "report/hotel_confirmation.xml",
        "report/hotel_rooming.xml",
        "report/hotel_invoice.xml",
        "report/hotel_invoice_voucher.xml",
    ],
    "demo": [],
    "application": False,
    "installable": True,
    "license": "OPL-1",
}
