{
    "name": "Travel Agency - Cars",
    "version": "16.0.1.0.0",
    "author": "OpenJAF, Business Solutions For Africa",
    "maintainer": "Vincent LUBA",
    "website": "https://www.biz-4-africa.com/odoo-travel",
    "category": "Sales",
    "description": ("Travel Agency - Cars"),
    "depends": ["travel_core"],
    "data": [
        "data/categories.xml",
        "data/attributes.xml",
        "views/product_template.xml",
        "views/sale_order_line.xml",
        "views/travel_line_details.xml",
        "wizard/car.xml",
        "report/car_voucher.xml",
        "security/ir.model.access.csv",
    ],
    "demo": ["data/demo_data.xml"],
    "application": False,
    "installable": True,
    "license": "OPL-1",
}
